pipeline {
    agent any

    environment {
        JAVA_HOME = "/usr/lib/jvm/java-21-openjdk-amd64"
        ANDROID_HOME = "/var/lib/jenkins/Android/Sdk"
        ANDROID_SDK_ROOT = "/var/lib/jenkins/Android/Sdk"
        PATH = "${env.PATH}:${JAVA_HOME}/bin:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/cmdline-tools/latest/bin:/opt/flutter/bin"
    }

    stages {
        stage('Checkout Repo') {
            steps {
                git 'https://github.com/Diekoo30/flutter_jenkins.git'
            }
        }

        stage('Build Flutter') {
            steps {
                dir('register_system/backend/flutter_app') {
                    sh 'flutter doctor -v'
                    sh 'flutter clean'
                    sh 'flutter pub get'
                    sh 'flutter build apk --release'
                }
            }
        }

        stage('Archive APK') {
            steps {
                archiveArtifacts artifacts: 'register_system/backend/flutter_app/build/app/outputs/flutter-apk/*.apk'
            }
        }
    }
}