pipeline {
    agent any

    environment {
        JAVA_HOME = "/usr/lib/jvm/java-21-openjdk-amd64"
        ANDROID_HOME = "/var/lib/jenkins/Android/Sdk"
        ANDROID_SDK_ROOT = "/var/lib/jenkins/Android/Sdk"
    }

    stages {
        stage('Checkout Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/Diekoo30/flutter_jenkins.git'
            }
        }

        stage('Build Flutter APK') {
            steps {
                dir('register_system/backend/flutter_app') {
                    sh '/opt/flutter/bin/flutter --version'
                    sh '/opt/flutter/bin/flutter clean'
                    sh '/opt/flutter/bin/flutter pub get'
                    sh '/opt/flutter/bin/flutter build apk --release'
                }
            }
        }

        stage('Archive APK') {
            steps {
                archiveArtifacts artifacts: 'register_system/backend/flutter_app/build/app/outputs/flutter-apk/*.apk'
            }
        }
    }
}
